### ISSUE TITLE
"print" instead of "say"

### ISSUE THREAD

**Issue by leszekdubiel** [LaurentRosenfeld/think_raku#4]
Instead of: 

"Note that in the print statement above, the final semi-colon has been omitted. When a
statement is the last code line of a block, immediately before the curly brace } closing
that code block, the final semi-colon is optional and may be omitted, though it might be
considered good form to include it."

should be: 

"Note that in the SAY statement above, the final semi-colon has been omitted. When a
statement is the last code line of a block, immediately before the curly brace } closing
that code block, the final semi-colon is optional and may be omitted, though it might be
considered good form to include it.

Tried to push change, but dont' have rights: 

diff --git a/book/Conditional_and_recursion.tex b/book/Conditional_and_recursion.tex
index 4dd5261..67eb303 100644
--- a/book/Conditional_and_recursion.tex
+++ b/book/Conditional_and_recursion.tex
@@ -482,7 +482,7 @@ if $n > 0 and $n < 20 and $n %% 2 {
 }
 \end{verbatim}
 %
-Note that in the say statement above, the final semi-colon 
+Note that in the print statement above, the final semi-colon 
 has been omitted. When a statement is the last code line of 
 a block, immediately before the curly brace {\tt \}} closing 
 that code block, the final semi-colon is optional and may

**Comment by LaurentRosenfeld** [comment]
Thank you for your comment. Well, yes, I understand your point, but I spent some time in section 1.3 explaining that a "say hello world;" code line is a print statement. I have to think more about it.

**Comment by LaurentRosenfeld** [comment]
OK, I decided to make the change: 

Note that in the {\tt say} statement above, ...

Thus closing the issue.
